version: "3.8"
services: 
    web:
        build: ./RedisSessionDemo
        container_name: "aspnet-core-redis-demo-web"
        ports: 
            - "5000:80"
        depends_on: 
            - redis
    redis:
        image: redis:6.0.6-alpine
        container_name: "redis_cache"
        ports: 
            - "6379:6379"    